version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: budget-sql-server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Pass123"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlvolume:/var/opt/mssql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7173:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=BudgetAppDB;User Id=sa;Password=YourStrong!Pass123;TrustServerCertificate=True;"
      JWT__ValidAudience: "http://localhost:3000"
      JWT__ValidIssuer: "http://localhost:7173"
      JWT__Secret: "ThisIsASecretKeyForJwtTokenGeneration123!"
      OpenAI__ApiKey: "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"
    depends_on:
      - sqlserver

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  sqlvolume:
