version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: budget-sql-server
    environment:
      SA_PASSWORD: "YourStrong!Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    build:
      context: ./BudgetTracker/BudgetTracker.Api
      dockerfile: Dockerfile
    container_name: budget-tracker-api
    depends_on:
      - sqlserver
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=BudgetAppDB;User=sa;Password=YourStrong!Pass123;TrustServerCertificate=True"

  frontend:
    build:
      context: ./budget-tracker-frontend
      dockerfile: Dockerfile
    container_name: budget-tracker-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  sql_data:
